apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: model-server:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2Gi"  # Increased for Mamba model
            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
          # normal config setup
          # - name: REDIS_HOST
          #   value: redis-db-service
          # - name: REDIS_PORT
          #   value: "6379"
          # - name: REDIS_PASSWORD
          #   value: aiwilltakeovertheworld
          # - name: MODEL_NAME  # Changed from TIMM_MODEL
          #   value: mambaout_base.in1k

          # From configuration map
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: hostname
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-config
                key: port
          - name: MODEL_NAME
            valueFrom:
              configMapKeyRef:
                name: model-server-config
                key: model_name
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: db_password