apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-server
  labels:
    app: ui-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-server
  template:
    metadata:
      labels:
        app: ui-server
    spec:
      containers:
      - name: ui-server
        image: ui-server:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "768Mi"     # Increased for dev environment
            cpu: "250m"         # Base CPU request
          limits:
            memory: "1.5Gi"     # Higher limit for dev environment
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          # normal config map
          # - name: REDIS_HOST
          #   value: redis-db-service
          # - name: REDIS_PORT
          #   value: "6379"
          # - name: REDIS_PASSWORD
          #   value: aiwilltakeovertheworld
          # - name: BACKEND_URL
          #   value: "http://web-server-service"

          # use config.cm fromc config file
          - name: WEB_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: web-server-config
                key: web_server_url

