apiVersion: v1
kind: Service
metadata:
  name: ui-server-service
spec:
  selector:
    app: ui-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-server-ingress
spec:
  rules:
    - host: fastapi.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-server-service
                port:
                  number: 80 